### ISSUE TITLE
New tagged release

### ISSUE THREAD

**Issue by druvus** [jnalanko/syotti#6]
Would it be possible to tag a new release to latest commit? I would like to add it to Bioconda so it would nice to use a version with the implemented SeqIO usage.

**Comment by druvus** [comment]
@jnalanko any opinions of tagging a new release?

**Comment by jnalanko** [comment]
Hi, sorry for the delay! I'll take care of this tomorrow (Monday).

**Comment by jnalanko** [comment]
I've created a new tagged release to the latest commit. So sorry for neglecting this issue for so long!
